//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Student_Register.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Student_Register.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRINT &apos;DATABASE CREATION PROCEDURE INITIALIZED&apos;
        ///PRINT &apos;&apos;
        ///PRINT &apos;CREATING DATABASE&apos;
        ///PRINT &apos;...&apos;
        ///
        ////* the database is created */ 
        ///CREATE DATABASE StudentRegister
        ///
        ///GO
        ///
        ///PRINT &apos;DONE&apos;
        ///PRINT &apos;&apos;
        ///PRINT &apos;&apos;
        ///
        ////* &apos;StudentRegister&apos; is selected as active database */
        ///USE StudentRegister
        ///
        ///PRINT &apos;CREATING TABLES&apos;
        ///PRINT &apos;...&apos;
        ///
        ////* the various tables are created */
        ///CREATE TABLE [dbo].[Courses]
        ///(
        ///    /* the &apos;ID&apos; column is set as primary key. it will start at 0 and will auto-incremnet by one for each new ent [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Database___Full_Script {
            get {
                return ResourceManager.GetString("Database___Full_Script", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HomeFormBackground {
            get {
                object obj = ResourceManager.GetObject("HomeFormBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon school_icon {
            get {
                object obj = ResourceManager.GetObject("school_icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon school_icon1 {
            get {
                object obj = ResourceManager.GetObject("school_icon1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
